[package]
name = "listings"
version = "0.1.0"
description = "Elixir listings program"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "listings"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "=0.26.0", features = ["init-if-needed"] }
anchor-spl = "=0.26.0"
winnow = "=0.4.1"
bridgesplit-program-utils = { git="ssh://git@github.com/bridgesplit/program-utils.git" }
num_enum = "0.5.6"


[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
