[package]
name = "listings"
version = "0.1.0"
description = "Elixir listings program"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "listings"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = {version = "0.26.0", feature= ["init-if-needed"]}
anchor-spl = "0.26.0"
mpl-token-metadata = { git = "https://github.com/metaplex-foundation/metaplex-program-library", features = ["no-entrypoint"] }
vault = {git="ssh://git@github.com/bridgesplit/bridgesplit-program.git", features = ["cpi"]}
anchor-mpl-token-metadata = {git="ssh://git@github.com/bridgesplit/bridgesplit-program.git"}
num_enum = "0.5.6"


[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
