[programs.mainnet]
bridgesplit_exchange = "mrkTzoWMVEBJ3AUrgd2eXNLXrnBuhhQRQyxahtaeTie"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/Downloads/mainnet_prod.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 /tests/"
